# fly.toml app configuration file generated for turtle-key-backend on 2025-03-10T21:01:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turtle-key-backend'
primary_region = 'sjc'

[build]
  command = "cd backend/turtle-key-backend && npm install && npm start"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
